version: '3.1'
services:
  db:
    image: docker.io/library/postgres
    restart: always
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPW
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"